-- カテゴリーテーブル削除
DROP TABLE IF EXISTS CATEGORY;
-- カテゴリー(カテゴリー定義テーブル)
CREATE TABLE CATEGORY (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  CAT_CODE VARCHAR(100) NOT NULL, -- カテゴリーコード
  CAT_NAME VARCHAR(225) NOT NULL UNIQUE, -- カテゴリー名
  CAT_TYPE VARCHAR(50) NULL, -- タイプ(ラジオボタン用ー 用途はとりあえず決まってないけど何か別のカテゴリーを設定したくなった時用)
  NOTE VARCHAR(255) NULL, -- メモ
  IMG_TYPE VARCHAR(50) NULL DEFAULT 'CATEGORY_ICON', -- 画像タイプ(画像テーブル内のタイプと連動)
  IMG_ID VARCHAR(100) NULL, -- 画像ID
  ACTIVE VARCHAR(100) NOT NULL DEFAULT '1', -- 有効化フラグ(有効化フラグ 1 = 有効 それ以外 = 無効)
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (CAT_CODE) -- プライマリーキー
);

-- 画像パステーブル削除
DROP TABLE IF EXISTS IMAGE;
-- 画像パス(画像パス保存テーブル)
CREATE TABLE IMAGE (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  IMG_ID VARCHAR(100) NOT NULL, -- 画像ID
  IMG_TYPE VARCHAR(255) NOT NULL, -- 画像のタイプ
  IMG_PATH VARCHAR(255) NOT NULL, -- 画像名
  IMG_NAME VARCHAR(255) NOT NULL, -- パス(相対/基本的にimagesフォルダ配下想定)
  NOTE VARCHAR(255) NULL, -- メモ
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (IMG_ID) -- プライマリーキー
);

-- 家計簿テーブル削除
DROP TABLE IF EXISTS BOOKS;
-- 家計簿(家計簿データ保存テーブル)
CREATE TABLE BOOKS (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  BOOKS_ID VARCHAR(100) NOT NULL, -- 家計簿ID
  USER_ID VARCHAR(50) NOT NULL, -- ユーザーID
  BOOKS_TYPE VARCHAR(100) NOT NULL, -- 帳簿の種類(収入、支出を選ぶ)
  BOOKS_DATE TIMESTAMP NOT NULL, -- 日付(収入日、購入日)
  BOOKS_PLACE VARCHAR(255) NOT NULL, -- 場所(収入元、購入先)
  CAT_CODE VARCHAR(100) NOT NULL, -- カテゴリーコード
  BOOKS_METHOD VARCHAR(100) NOT NULL, -- 方法(受け取り方、支払い方)
  BOOKS_AMMOUNT INTEGER NOT NULL, -- 金額
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (BOOKS_ID, USER_ID) -- プライマリーキー
);

-- コードリストテーブル削除
DROP TABLE IF EXISTS CODE_LIST;
-- コードリスト(コード定義テーブル(ヘッダー))
CREATE TABLE CODE_LIST (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  LIST_NAME VARCHAR(50) NOT NULL, -- リストネーム
  DESCRIPTION VARCHAR(255) NULL, -- 説明
  EDITABLE VARCHAR(1) NULL DEFAULT '1', -- 編集可否(編集可否 1 = 可能 それ以外 = 不可)
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (LIST_NAME) -- プライマリーキー
);

-- コードルックアップテーブル削除
DROP TABLE IF EXISTS CODE_LOOKUP;
-- コードルックアップ(コード定義テーブル(明細))
CREATE TABLE CODE_LOOKUP (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  LIST_NAME VARCHAR(50) NOT NULL, -- リストネーム
  CODE VARCHAR(64) NOT NULL, -- コード
  DESCRIPTION VARCHAR(255) NULL, -- 説明
  SHORT_VALUE VARCHAR(64) NULL, -- 値(短)(コードに対する値(短縮形)を設定)
  LONG_VALUE VARCHAR(255) NULL, -- 値(長)(コードに対する値(全文)を設定)
  EDITABLE VARCHAR(1) NOT NULL DEFAULT '1', -- 編集可否(編集可否 1 = 可能 それ以外 = 不可)
  ACTIVE VARCHAR(100) NOT NULL DEFAULT '1', -- 有効化フラグ(有効化フラグ 1 = 有効 それ以外 = 無効)
  SEQUENCE INTEGER NULL DEFAULT 1000, -- シークエンス(コードリストに対する子コード同士の順番を定義)
  UDF1 VARCHAR(255) NULL, -- 備考(なんでも)1
  UDF2 VARCHAR(255) NULL, -- 備考(なんでも)2
  UDF3 VARCHAR(255) NULL, -- 備考(なんでも)3
  UDF4 VARCHAR(255) NULL, -- 備考(なんでも)4
  UDF5 VARCHAR(255) NULL, -- 備考(なんでも)5
  UDF6 VARCHAR(255) NULL, -- 備考(なんでも)6
  UDF7 VARCHAR(255) NULL, -- 備考(なんでも)7
  NOTE VARCHAR(255) NULL, -- メモ
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (LIST_NAME, CODE) -- プライマリーキー
);

-- チャートカラーマスタテーブル削除
DROP TABLE IF EXISTS TEMPLATE_CHARTCOLOUR;
-- チャートカラーマスタ(図の表示に使用するrgbaの組み合わせを管理するマスタ)
CREATE TABLE TEMPLATE_CHARTCOLOUR (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  TEMPLATE_ID VARCHAR(50) NOT NULL, -- 色の組み合わせID
  TEMPLATE_NAME VARCHAR(255) NOT NULL, -- 色の組み合わせ名
  USER_ID VARCHAR(50) NOT NULL, -- ユーザーID
  ACTIVE VARCHAR(100) NOT NULL DEFAULT '0', -- 有効化フラグ(現在設定されている 1 = 有効 それ以外 = 無効)
  SEED_COEFF_R INTEGER NOT NULL, -- シード値算出に使用する係数(R)(この係数を用いてシード値を算出しRGBAのRの値を算出する)
  SEED_COEFF_G INTEGER NOT NULL, -- シード値算出に使用する係数(G)(この係数を用いてシード値を算出しRGBAのGの値を算出する)
  SEED_COEFF_B INTEGER NOT NULL, -- シード値算出に使用する係数(B)(この係数を用いてシード値を算出しRGBAのBの値を算出する)
  NOTE VARCHAR(255) NULL, -- メモ
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (TEMPLATE_ID) -- プライマリーキー
);

-- アカウントテーブル削除
DROP TABLE IF EXISTS ACCOUNT;
-- アカウント(アカウント情報保持テーブル)
CREATE TABLE ACCOUNT (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  USER_ID VARCHAR(50) NOT NULL, -- ユーザーID
  PASSWORD VARCHAR(255) NOT NULL, -- パスワード
  USER_NAME VARCHAR(255) NOT NULL, -- ユーザー名
  ACCOUNT_TYPE VARCHAR(50) NOT NULL, -- アカウント種別
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (USER_ID) -- プライマリーキー
);

-- デフォルトカテゴリーテーブル削除
DROP TABLE IF EXISTS DEFAULT_CATEGORY;
-- デフォルトカテゴリー(家計簿につける項目ごとのデフォルトカテゴリーを設定)
CREATE TABLE DEFAULT_CATEGORY (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  USER_ID VARCHAR(50) NOT NULL, -- ユーザーID
  BOOKS_PLACE VARCHAR(255) NOT NULL, -- 場所(収入元、購入先)
  BOOKS_TYPE VARCHAR(100) NOT NULL, -- 帳簿の種類(収入、支出を選ぶ)
  BOOKS_METHOD VARCHAR(100) NOT NULL, -- 方法(受け取り方、支払い方)
  CAT_CODE VARCHAR(100) NOT NULL, -- カテゴリーコード
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (USER_ID, BOOKS_PLACE, BOOKS_TYPE, BOOKS_METHOD) -- プライマリーキー
);

