-- アカウントテーブル削除
DROP TABLE IF EXISTS ACCOUNT;
-- アカウント(アカウント情報保持テーブル)
CREATE TABLE ACCOUNT (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  USER_ID VARCHAR(50) NOT NULL, -- ユーザーID
  PASSWORD VARCHAR(255) NOT NULL, -- パスワード
  USER_NAME VARCHAR(255) NOT NULL, -- ユーザー名
  ACCOUNT_TYPE VARCHAR(50) NOT NULL, -- アカウント種別
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (USER_ID) -- プライマリーキー
);

