-- 画像パステーブル削除
DROP TABLE IF EXISTS IMAGE;
-- 画像パス(画像パス保存テーブル)
CREATE TABLE IMAGE (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  IMG_ID VARCHAR(100) NOT NULL, -- 画像ID
  IMG_TYPE VARCHAR(255) NOT NULL, -- 画像のタイプ
  IMG_PATH VARCHAR(255) NOT NULL, -- 画像名
  IMG_NAME VARCHAR(255) NOT NULL, -- パス(相対/基本的にimagesフォルダ配下想定)
  NOTE VARCHAR(255) NULL, -- メモ
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (IMG_ID) -- プライマリーキー
);

