-- デフォルトカテゴリーテーブル削除
DROP TABLE IF EXISTS DEFAULT_CATEGORY;
-- デフォルトカテゴリー(家計簿につける項目ごとのデフォルトカテゴリーを設定)
CREATE TABLE DEFAULT_CATEGORY (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  DEFAULT_CATEGORY_ID VARCHAR(100) NOT NULL DEFAULT GEN_RANDOM_UUID(), -- デフォルトカテゴリーID
  USER_ID VARCHAR(50) NOT NULL, -- ユーザーID
  BOOKS_PLACE VARCHAR(255) NOT NULL, -- 場所(収入元、購入先)
  BOOKS_TYPE VARCHAR(100) NOT NULL, -- 帳簿の種類(収入、支出を選ぶ)
  BOOKS_METHOD VARCHAR(100) NOT NULL, -- 方法(受け取り方、支払い方)
  BOOKS_AMMOUNT_MIN INTEGER NOT NULL DEFAULT -1, -- 金額(最小値)(金額(最小値) マイナスの場合は検索対象から除外)
  BOOKS_AMMOUNT_MAX INTEGER NOT NULL DEFAULT -1, -- 金額(最大値)(金額(最大値) マイナスの場合は検索対象から除外)
  CAT_CODE VARCHAR(100) NOT NULL, -- カテゴリーコード
  REGEX_ENABLED VARCHAR(1) NOT NULL DEFAULT '0', -- 正規表現使用可否(正規表現使用可否 1 = 使用 それ以外 = 使用しない)
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (DEFAULT_CATEGORY_ID, USER_ID) -- プライマリーキー
);
