-- カテゴリーテーブル削除
DROP TABLE IF EXISTS CATEGORY;
-- カテゴリー(カテゴリー定義テーブル)
CREATE TABLE CATEGORY (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  CAT_CODE VARCHAR(100) NOT NULL, -- カテゴリーコード
  CAT_NAME VARCHAR(225) NOT NULL UNIQUE, -- カテゴリー名
  CAT_TYPE VARCHAR(50) NULL, -- タイプ(ラジオボタン用ー 用途はとりあえず決まってないけど何か別のカテゴリーを設定したくなった時用)
  NOTE VARCHAR(255) NULL, -- メモ
  IMG_TYPE VARCHAR(50) NULL DEFAULT 'CATEGORY_ICON', -- 画像タイプ(画像テーブル内のタイプと連動)
  IMG_ID VARCHAR(100) NULL, -- 画像ID
  ACTIVE VARCHAR(100) NOT NULL DEFAULT '1', -- 有効化フラグ(有効化フラグ 1 = 有効 それ以外 = 無効)
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (CAT_CODE) -- プライマリーキー
);

