-- 家計簿テーブル削除
DROP TABLE IF EXISTS BOOKS;
-- 家計簿(家計簿データ保存テーブル)
CREATE TABLE BOOKS (
  SERIAL_KEY SERIAL NOT NULL UNIQUE, -- シリアルキー
  BOOKS_ID VARCHAR(100) NOT NULL, -- 家計簿ID
  BOOKS_TYPE VARCHAR(100) NOT NULL, -- 帳簿の種類(収入、支出を選ぶ)
  BOOKS_DATE TIMESTAMP NOT NULL, -- 日付(収入日、購入日)
  BOOKS_PLACE VARCHAR(255) NOT NULL, -- 場所(収入元、購入先)
  CAT_CODE VARCHAR(100) NOT NULL, -- カテゴリーコード
  BOOKS_METHOD VARCHAR(100) NOT NULL, -- 方法(受け取り方、支払い方)
  BOOKS_AMMOUNT INTEGER NOT NULL, -- 金額
  INS_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 登録日時
  INS_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 登録ユーザー
  UPD_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 更新日時
  UPD_USER VARCHAR(50) NOT NULL DEFAULT CURRENT_USER, -- 更新ユーザー
  PRIMARY KEY (BOOKS_ID) -- プライマリーキー
);

